# This script is meant to be run from the root of the zyn-fusion-build repo.
# It builds ZynFusion's tarballs for Ubuntu and Windows (cross-build).

# Uncomment this line if your system requires sudo to run docker.
#SUDO=sudo

# Version number included in the tarballs generated by the build process.
# It must match the version number at the top of Common.mk.
# This is required because 'docker cp' doesn't support wildcards.
ZYNADD_VERSION=$(cat ./version.txt)

#### No user parameters below this line ####
set -e 
DOCKER="${SUDO} docker"

# Base image for Linux builds
${DOCKER} build -t zf-ubuntu-linux-img -f docker-builders/ubuntu-linux.dockerfile .

# Demo
${DOCKER} run --name zf-ubuntu-linux zf-ubuntu-linux-img make MODE=demo PARALLEL=1 -f Makefile.linux.mk
${DOCKER} cp zf-ubuntu-linux:/z/build/zyn-fusion-linux-64bit-${ZYNADD_VERSION}-demo.tar.bz2 .
${DOCKER} rm zf-ubuntu-linux

# Release
${DOCKER} run --name zf-ubuntu-linux zf-ubuntu-linux-img make MODE=release PARALLEL=1 -f Makefile.linux.mk
${DOCKER} cp zf-ubuntu-linux:/z/build/zyn-fusion-linux-64bit-${ZYNADD_VERSION}-release.tar.bz2 .
${DOCKER} rm zf-ubuntu-linux

# Base image for cross-compilation Windows builds
${DOCKER} build -t zf-ubuntu-w64-img -f docker-builders/ubuntu-windows.dockerfile .

# Cross-compilation demo
${DOCKER} run --name zf-ubuntu-w64 zf-ubuntu-w64-img make MODE=demo PARALLEL=1 -f Makefile.windows.mk
${DOCKER} cp zf-ubuntu-w64:/z/build/zyn-fusion-windows-64bit-${ZYNADD_VERSION}-demo.zip .
${DOCKER} rm zf-ubuntu-w64

# Cross-compilation release
${DOCKER} run --name zf-ubuntu-w64 zf-ubuntu-w64-img make MODE=release PARALLEL=1 -f Makefile.windows.mk
${DOCKER} cp zf-ubuntu-w64:/z/build/zyn-fusion-windows-64bit-${ZYNADD_VERSION}-release.zip .
${DOCKER} rm zf-ubuntu-w64

# Cleanup
${DOCKER} rmi zf-ubuntu-linux-img
${DOCKER} rmi zf-ubuntu-w64-img
